dist: xenial
language: node_js
node_js: node
cache: yarn
env:
  global:
  - secure: E0J+RuXknesJscVTDTP2gwpZusvO5hD4La1pxUhslL6DbCwrQWz0fnWCNuwbqFkBVJABZOQ5NGeFcjTtkYctXo7pHSqMjhJEYSzwJtSXyr/vTG9aIECR2Sh4Cluz/BJM3OI/v1y+9hYcMvjy9oaKxtB0UVtg++5cGgHcLlpsOfjehVNqVhgn5v3n1YJuw/RWOnKDk+NKvdtlh812lODP1m7vgOzFYzdNi9sWzfGm8YUn6sQvgq+jZ62GLKuEXXK1PKmWIfmEGN/tJtTyMDOezYoZszTTiLRE2SD64DxpRmXA2Em3AXqayQJqNusT/p5UtTMuSBCMDg6FI7OXwG9pnRxGi1Rz1m2MTKScfYxcakgNJCOXBuS7CpeTiSnIiV9E4jmwvoTEjPxHIarnFfyGYi2XnwqQnZew/A9hSUdxM/f20QOINU48J92bzB0X1lKkwFETkihUjPGv1Ctmxg5YQrUcNEEcfyoMouGy8iA4hygH0qVHgCOE/uHfnwExNwaceWiQD7C5Cxnhfl4Ip5YUUZ2WtU6DE4LJRKZcLMCKXYq7hbvrA9kEoKqyujE8KY4Fl+52p3ZmhjkjKEUOEvgBrl6UBEnuR0HIm7YmnPrU/2rA8hMywciXTP8dyAUl8KBSjOOsTQhoDWD5MJwaIwe3VyGBKAV6HYgXJ4HdM6GuZD4=
  - secure: afZSjbhGp0+/NOjxJZAZEYXVxh09F/RrU/sD7SXgHUiPCBuHXiwXSHxIkK7eBYx9Vq3cqv5m5C0L5ob/qwvrlzU144wKgAvxshKF7vvo3Wx6V/8X24sIOxF9XbQLeEQXrrDHMAREbYe7tLG+HaqyQ6E9F0nuxRe7xOE9yJ51h4YUMqCc2zezgPeiup64d4jp6RSkKUu2hbcUlkOfKqu5K5D0u7ZOJga6ZQA2/XcBj/RvXtRR2kmvFMt/8onWnoDlw+PXbW/JSFUBuqzBmhgWNOwPx8hExSJ730D4a7Tiq7nvFn9sezqUWDevJ4hzfC6bPez4Hd4Tla893Xa9klI7Pp0orA02pXdAiMRi9J+kcM53rzUR6wk2dhWNn+TuYaGFb5V40kt1fqwEVoBXa851gSsQS8KIDboKfYQGWFbl5fwqg6Ur3ctEGjsCudUZZYA8gLqEUuBWLjuSTAEHc597oAbceqsFWXP+uzSDsZL3ic7FomDo2OgalvUgMkydK35BEXoSvVUbBWiWbuMd1uJrm0U4YKEn7/YpH2orYevPaRLmfvnshhopdt4QMx2hL3WFqWo0nye9Yh9pc7tX2vQ39Lev1pjxCIMfTQRhv7/ksQvBiNOuSJVQ+iHV9pdgqj2UXjS+TU1TGT19+wbnBn5P+7VgEiZYSWaofOHoEJwXZQQ=
branches:
  only:
    - master
deploy:
  provider: script
  skip_cleanup: true
  script:
  - yarn release
